<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

namespace Hyperf\Odin\Api\Providers\OpenAI;

use Hyperf\Context\ApplicationContext;
use Psr\SimpleCache\CacheInterface;
use Throwable;

/**
 * Cache manager for reasoning_details (Gemini OpenAI-compatible format).
 *
 * reasoning_details contains the model's thought signature and is required for
 * multi-turn tool calling with Gemini 3 models. It must be passed back in the
 * assistant message of subsequent requests to maintain the chain of reasoning.
 *
 * The cache is keyed at the assistant-message level (derived from all tool_call_ids),
 * not at individual tool level. One assistant turn = one cache entry.
 *
 * @see https://ai.google.dev/gemini-api/docs/thought-signatures
 */
class ReasoningDetailsCache
{
    private const CACHE_PREFIX = 'openai:reasoning_details:';

    /**
     * Default cache TTL in seconds (12 hours).
     * reasoning_details validity is tied to the conversation session, no official TTL documented.
     */
    private const CACHE_TTL = 43200;

    /**
     * Generate a stable cache key representing the entire assistant message.
     * Uses all tool_call_ids in their natural order to identify the assistant turn uniquely.
     *
     * @param string[] $toolCallIds All tool_call_ids from the assistant message
     */
    public static function generateAssistantKey(array $toolCallIds): string
    {
        return md5(implode('|', $toolCallIds));
    }

    /**
     * Store reasoning_details for an assistant message (identified by all its tool_call_ids).
     *
     * @param string $assistantKey Key generated by generateAssistantKey()
     * @param array $reasoningDetails The reasoning_details array from the response
     */
    public static function store(string $assistantKey, array $reasoningDetails): void
    {
        $cache = self::getCacheDriver();
        if ($cache === null) {
            return;
        }
        $cache->set(self::CACHE_PREFIX . $assistantKey, $reasoningDetails, self::CACHE_TTL);
    }

    /**
     * Retrieve reasoning_details for an assistant message.
     *
     * @param string $assistantKey Key generated by generateAssistantKey()
     * @return null|array The reasoning_details array, or null if not found
     */
    public static function get(string $assistantKey): ?array
    {
        $cache = self::getCacheDriver();
        if ($cache === null) {
            return null;
        }
        $data = $cache->get(self::CACHE_PREFIX . $assistantKey);
        return is_array($data) ? $data : null;
    }

    /**
     * Delete reasoning_details for an assistant message.
     *
     * @param string $assistantKey Key generated by generateAssistantKey()
     */
    public static function delete(string $assistantKey): void
    {
        $cache = self::getCacheDriver();
        if ($cache === null) {
            return;
        }
        $cache->delete(self::CACHE_PREFIX . $assistantKey);
    }

    /**
     * Get cache driver instance.
     *
     * @return null|CacheInterface Returns null if cache is not available
     */
    private static function getCacheDriver(): ?CacheInterface
    {
        try {
            if (! ApplicationContext::hasContainer()) {
                return null;
            }
            $cache = ApplicationContext::getContainer()->get(CacheInterface::class);
            return $cache instanceof CacheInterface ? $cache : null;
        } catch (Throwable) {
            return null;
        }
    }
}
