<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

namespace Hyperf\Odin\Api\Providers\Gemini;

use Hyperf\Context\ApplicationContext;
use Hyperf\Odin\Contract\Message\MessageInterface;
use Hyperf\Odin\Exception\RuntimeException;
use Psr\SimpleCache\CacheInterface;

/**
 * Manager for Gemini thought signatures.
 *
 * Thought signatures are cryptographic representations of the model's internal thinking process,
 * used to preserve reasoning context across multi-turn interactions.
 *
 * @see https://ai.google.dev/gemini-api/docs/thought-signatures
 */
class ThoughtSignatureCache
{
    private const CACHE_PREFIX = 'gemini:thought_signature:';

    private const CACHE_TTL = 43200;

    /**
     * Generate a stable cache key representing the entire assistant message.
     * Uses all tool_call_ids in their natural order to identify the assistant turn uniquely.
     * Thought signature belongs to the model's thinking turn as a whole, not to individual tool calls.
     *
     * @param string[] $toolCallIds All tool_call_ids from the assistant message
     */
    public static function generateAssistantKey(array $toolCallIds): string
    {
        return md5(implode('|', $toolCallIds));
    }

    /**
     * Store a thought signature for an assistant message (identified by all its tool_call_ids).
     *
     * @param string $assistantKey Key generated by generateAssistantKey()
     * @param string $thoughtSignature The thought signature from Gemini response
     */
    public static function store(string $assistantKey, string $thoughtSignature): void
    {
        $cache = self::getCacheDriver();
        $cache->set(self::CACHE_PREFIX . $assistantKey, $thoughtSignature, self::CACHE_TTL);
    }

    /**
     * Retrieve a thought signature for an assistant message.
     *
     * @param string $assistantKey Key generated by generateAssistantKey() or generateMessageKey()
     * @return null|string The thought signature, or null if not found
     */
    public static function get(string $assistantKey): ?string
    {
        $cache = self::getCacheDriver();
        $signature = $cache->get(self::CACHE_PREFIX . $assistantKey);
        return is_string($signature) ? $signature : null;
    }

    /**
     * Delete a thought signature for an assistant message.
     *
     * @param string $assistantKey Key generated by generateAssistantKey() or generateMessageKey()
     */
    public static function delete(string $assistantKey): void
    {
        $cache = self::getCacheDriver();
        $cache->delete(self::CACHE_PREFIX . $assistantKey);
    }

    /**
     * Check if cache is available.
     */
    public static function isAvailable(): bool
    {
        return self::getCacheDriver() !== null;
    }

    /**
     * Calculate cumulative context hash from message list.
     * This creates a unique hash based on all previous messages in the conversation.
     *
     * @param MessageInterface[] $messages Array of messages
     * @param int $upToIndex Calculate hash up to this index (exclusive)
     * @return string The cumulative context hash
     */
    public static function calculateContextHash(array $messages, int $upToIndex): string
    {
        $hash = '';
        for ($i = 0; $i < $upToIndex && $i < count($messages); ++$i) {
            $message = $messages[$i];
            // Accumulate hash = md5(previous_hash + message_hash)
            // Using getHash() which includes all message properties
            $hash = md5($hash . $message->getHash());
        }
        return $hash;
    }

    /**
     * Generate cache key for normal message thought signature.
     * Uses context hash to ensure uniqueness within a conversation.
     *
     * @param string $contextHash The cumulative context hash
     * @param string $content The message content
     * @return string The cache key
     */
    public static function generateMessageKey(string $contextHash, string $content): string
    {
        return 'msg_' . $contextHash . '_' . md5($content);
    }

    private static function getCacheDriver(): CacheInterface
    {
        $cache = ApplicationContext::getContainer()->get(CacheInterface::class);
        if (! $cache instanceof CacheInterface) {
            throw new RuntimeException('CacheInterface must have a valid cache driver instance.');
        }
        return $cache;
    }
}
